### ISSUE TITLE
Erro método post

### ISSUE THREAD

**Issue by luizuk** [lucasnhimi/todo-app#1]
Lucas, bom dia, primeiramente muito obrigado por todos os conhecimentos do vídeo e do projeto.

Durante o desenvolvimento tive um problema no método post pra salvar as todos no banco. O método GET está funcionando corretamente, porém o método POST está dando um problema de Network e não salva os dados. Se eu inserir manualmente os dados estão chegando certinho.

Pesquisei em vários lugares e acabei ficando ainda mais perdido, parece que é um erro no formato da requisição, mas como eu não tenho tanta experiência com requisições eu decidi compartilhar isso aqui pra ver se você consegue pensar junto comigo ou solucionar talvez a dúvida de mais alguém.

Meus arquivos db, todo.ts e todolist.tsx (equivalente ao seu index.tsx) estão exatamente iguais aos seus e eu estou tendo esse erro abaixo na hora de inserir no banco.

Se precisar de mais informações eu envio aqui.

![image](https://user-images.githubusercontent.com/35464652/166242544-2dba1a43-7230-4dd0-afc7-cef204bd725d.png)

**Comment by lucasnhimi** [comment]
Acesse nossa comunidade e lá vamos te ajudar a solucionar seu problema.

Na descrição do vídeo tem o link da comunidade no discord

**Comment by luizuk** [comment]
Ok, envio lá!
